#ifndef _MAGIA_MESH_ADDR_MAP_INCLUDE_GUARD_
#define _MAGIA_MESH_ADDR_MAP_INCLUDE_GUARD_

#define PERIPH_OFFSET 0x

#define FETCH_EN_OFFSET          (PERIPH_OFFSET + 0x)

#define BOOT_ADDR_TILE_0_OFFSET  (PERIPH_OFFSET + 0x)



#endif