#ifndef _MAGIA_REG_DEFS_
#define _MAGIA_REG_DEFS_

#define MAGIA_MESH_BUSY_REG_OFFSET 0x
#define MAGIA_MESH_RETURN_REG_OFFSET 0x

#define MAGIA_MESH_CLK_GATE_EN_REG_OFFSET 0x
#define MAGIA_MESH_CLK_GATE_EN_CLUSTER_0_CLK_GATE_EN_BIT 0





#endif  // _MAGIA_REG_DEFS_